// const baseUrl = '/api'
const baseUrl = 'http://localhost:3000/api'
export default {
  userinfo: baseUrl + '/login',
  sendmsg: baseUrl + '/sendmsg',
  register:baseUrl + '/register',
  saveinfo:baseUrl + '/saveinfo',
  getInfo:baseUrl + '/getInfo',
  saveDiary:baseUrl + '/saveDiary',
  getDiaryList:baseUrl + '/getDiaryList',
  setpwd:baseUrl + '/setpwd',
  saveAnniversary:baseUrl + '/saveAnniversary',
  getAnniversary:baseUrl + '/getAnniversary',
  getTimeline:baseUrl + '/getTimeline',
  getdetail:baseUrl + '/getdetail',
  savedetail:baseUrl + '/savedetail',
  resubmitDiary:baseUrl + '/resubmitDiary',
  todelDiary:baseUrl + '/todelDiary',
  getAllmoodpush:baseUrl + '/getAllmoodpush',
  getmoodPushContent:baseUrl + '/getmoodPushContent',
  addTreeMain:baseUrl + '/addTreeMain',
  userOpinion:baseUrl + '/userOpinion',
  getTreeList:baseUrl + '/getTreeList',
  getHotList:baseUrl + '/getHotList',
  getAllMsg:baseUrl + '/getAllMsg',
  delMsg:baseUrl + '/delMsg',
  getTreeDetail:baseUrl + '/getTreeDetail',
  getUserTree:baseUrl + '/getUserTree',
  addComment:baseUrl + '/addComment',
  getComment:baseUrl + '/getComment',
  Thumbs:baseUrl + '/Thumbs',
  getThumbs:baseUrl + '/getThumbs',
  getThumbsUser:baseUrl + '/getThumbsUser',
  delDot:baseUrl + '/delDot',
  findDot:baseUrl + '/findDot',
  CommentThumbs:baseUrl + '/CommentThumbs',
  commentCount:baseUrl + '/commentCount',
}

